#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

cd "$ROOT/demo-1-cpu-hpa"
go test ./...
go vet ./...

cd "$ROOT/demo-2-redpanda-keda"
go test ./...
go vet ./...
