apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: consumer-kafka-lag
  namespace: demo-2-redpanda-keda
spec:
  scaleTargetRef:
    name: consumer
  pollingInterval: 5
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: redpanda.demo-2-redpanda-keda.svc.cluster.local:9092
        topic: demo-work
        consumerGroup: demo-work-consumer-group
        lagThreshold: "50"
        activationLagThreshold: "1"
