FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/producer ./cmd/producer

FROM alpine:3.20

WORKDIR /app
RUN adduser -D -u 10001 appuser

COPY --from=builder /out/producer /app/producer

USER appuser
EXPOSE 8080

ENTRYPOINT ["/app/producer"]
