FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/consumer ./cmd/consumer

FROM alpine:3.20

WORKDIR /app
RUN adduser -D -u 10001 appuser

COPY --from=builder /out/consumer /app/consumer

USER appuser
EXPOSE 8080

ENTRYPOINT ["/app/consumer"]
